import { FC, ReactNode } from 'react'
import Sidebar from '@/src/components/Sidebar'

const Footer = () => {
  return <footer className='py-3 text-center opacity-40'>This chatbot responses are generated by OpenAI&apos;s GPT. As GPT may occasionally produce inaccurate or misleading data, always verify AI messages when they contain critical information. </footer>
}

const Layout: FC<{ children: ReactNode, onNewChat: () => void }>  = ({ children, onNewChat }) => {

  return (
    <div className='flex h-screen'>
      <Sidebar onNewChat={onNewChat} />
      <main className ="w-full">
        {children}
        <Footer />  
      </main> 
    </div>
  )
}

export default Layout


